name: Security audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo install cargo-audit
          cargo audit --ignore RUSTSEC-2022-0033 --ignore RUSTSEC-2022-0032 # openssl bug unaffected
