name: Build and push Docker images
on:
  push:
    # tags:
    #   - v[0-9]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/kube-depre

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and push
        run: |
          PACKAGE_VERSION=${{ steps.get_version.outputs.VERSION }}
          KUBE_DEPRE_IMAGE=$DOCKER_REPO:$PACKAGE_VERSION
          KUBE_DEPRE_IMAGE_LATEST=$DOCKER_REPO:latest
          docker buildx build \
            --tag $KUBE_DEPRE_IMAGE \
            --tag $KUBE_DEPRE_IMAGE_LATEST \
            --platform linux/amd64 \
            --push \
            -f ./docker/Dockerfile .
